# package.yml
packages:
  - name: "bp_data_cleaning"
    version: "1.0.0"
    description: "A dbt package for cleaning and parsing blood pressure data."
    repository: "https://github.com/pikki/unifiedmodel"
"
